language: go

sudo: false

go:
  - '1.11'

git:
  depth: 1

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - goveralls -v -race -service=travis-ci
